### ISSUE TITLE
Could not find a declaration file for module node-fetch

### ISSUE THREAD

**Issue by mskian** [wildlifehexagon/node-world-cup#1]
Hi I spotted this error on VS Code for the declaration `const fetch = require("node-fetch")`

```
[ts]
Could not find a declaration file for module 'node-fetch'. '/home/user/myfolder/node-world-cup/node_modules/node-fetch/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/node-fetch` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-fetch';`
```
`const ora = require("ora")` 

```
[ts] File is a CommonJS module; it may be converted to an ES6 module.
(property) require: any
```

**Comment by erichartline** [comment]
Hmm I'm also using VS Code and not seeing these warnings. Not sure where the Typescript stuff is coming from since my project doesn't use that. Is it possible there is something with your VS Code config that is causing these issues? Thanks for checking out my app, BTW!

**Comment by mskian** [comment]
it's Fixed :smiley:  

Why not adding Custom error Message for country command?
while accidentally running the below command it has shown the node `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toUpperCase' of undefined` Error
Better add a Custom message for this & add country code too...
```
worldcup country
```

**Comment by erichartline** [comment]
Good catch. I added a patch to make sure the user specifies a code when using the `country` command.

**Comment by mskian** [comment]
`worldcup country -c isl` did not fetch the output returns with 

```
You need to enter a FIFA country code to use this command. Try something like:
      worldcup country -c isl
```

another request Add Proper output text alignments for `today`, `current`, `country` outputs

**Comment by erichartline** [comment]
I'm going to revise that whole `country` command when I get a chance later. What do you mean about text alignments? Just some indentation?

**Comment by mskian** [comment]
Proper text Alignments for outputs

![ftlive-18-op](https://user-images.githubusercontent.com/10300271/41556071-44c20e7c-7357-11e8-8cb4-10c39e85d337.png)

**Comment by erichartline** [comment]
Sorry, still not sure what you're asking about the text alignments. That's how I intended it to look, but I'm open to different visual ideas.

I also fixed the `country` command.
