### ISSUE TITLE
Could not load remote data Error: command option not supported

### ISSUE THREAD

**Issue by boris61** [wildlifehexagon/node-world-cup#2]
I get this error with any command other than current or today. Any help?

`at IncomingMessage. (PATH\worldcup\bin\worldcup:23:30)
at emitNone (events.js:110:20)
at IncomingMessage.emit (events.js:207:7)
at endReadableNT (_stream_readable.js:1056:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by erichartline** [comment]
I think the API server was having issues last night so that could be why it didn't load the remote data. Can you try again? Also, what version of Node.js are you using?

**Comment by boris61** [comment]
Nope, still not working. Node version is 8.8.1

**Comment by erichartline** [comment]
Hmm, I tried it out with Node 8.8.1 and didn't run into any issues. Not sure what's causing this, unfortunately :(
